# Generated by Django 5.0.6 on 2024-05-24 13:40

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='client/profileImg/')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('country', models.CharField(default='', max_length=15)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('linkedIn_url', models.URLField(blank=True, max_length=500, null=True)),
                ('desired_job_title', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(default='', max_length=100)),
                ('institution_location', models.CharField(default='', max_length=100)),
                ('program_pursued', models.CharField(default='', max_length=100)),
                ('field_of_study', models.CharField(default='', max_length=100)),
                ('graduated', models.BooleanField(default=True)),
                ('graduation_month', models.CharField(blank=True, max_length=100, null=True)),
                ('graduation_year', models.CharField(blank=True, max_length=100, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(default='', max_length=100)),
                ('company', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=15)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(default='', max_length=100)),
                ('start_month', models.CharField(blank=True, max_length=100, null=True)),
                ('start_year', models.CharField(blank=True, max_length=100, null=True)),
                ('end_month', models.CharField(blank=True, max_length=100, null=True)),
                ('end_year', models.CharField(blank=True, max_length=100, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_summary', ckeditor_uploader.fields.RichTextUploadingField()),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
        ),
    ]
