# Generated by Django 5.0.6 on 2024-05-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_template_about_user_template_course_pursued_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='about_user',
        ),
        migrations.RemoveField(
            model_name='template',
            name='course_pursued',
        ),
        migrations.RemoveField(
            model_name='template',
            name='email',
        ),
        migrations.RemoveField(
            model_name='template',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='template',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='template',
            name='location',
        ),
        migrations.RemoveField(
            model_name='template',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='template',
            name='profile_picture',
        ),
        migrations.AlterField(
            model_name='template',
            name='template_file',
            field=models.FileField(upload_to='resumes/'),
        ),
    ]
