# Generated by Django 5.0.6 on 2024-05-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_remove_template_about_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='template',
            name='categories',
            field=models.ManyToManyField(related_name='templates', to='builder.templatecategory'),
        ),
    ]
