# Generated by Django 5.0.6 on 2024-06-02 14:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0006_template_num_educations_template_num_experiences_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='num_educations',
        ),
        migrations.RemoveField(
            model_name='template',
            name='num_experiences',
        ),
        migrations.RemoveField(
            model_name='template',
            name='num_hobbies',
        ),
        migrations.RemoveField(
            model_name='template',
            name='num_languages',
        ),
        migrations.RemoveField(
            model_name='template',
            name='num_references',
        ),
        migrations.RemoveField(
            model_name='template',
            name='num_skills',
        ),
        migrations.AlterField(
            model_name='template',
            name='description',
            field=ckeditor.fields.RichTextField(default='Who should use this?'),
        ),
    ]
