# Generated by Django 5.0.6 on 2024-06-07 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0007_remove_template_num_educations_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Template',
        ),
        migrations.DeleteModel(
            name='TemplateCategory',
        ),
    ]
