# Generated by Django 5.0.6 on 2024-05-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_client_user_educations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='LinkedIn',
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='linkedIn_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='proffesion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
