# Generated by Django 5.0.6 on 2024-05-24 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_client_proffesion_client_desired_job_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='client',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='client',
        ),
        migrations.DeleteModel(
            name='education',
        ),
        migrations.DeleteModel(
            name='skill',
        ),
        migrations.DeleteModel(
            name='client',
        ),
        migrations.DeleteModel(
            name='experience',
        ),
    ]
